### ISSUE TITLE
Trying to run the model on an AWS instance but getting many errors...

### ISSUE THREAD

**Issue by aced125** [openai/summarize-from-feedback#2]
Hi,

I spun up an AWS p3.2xlarge (with a V100), and tried to run the code. Followed all azure setup instructions.

First error I got was:

```
blobfile.common.Request Failure: message=unexpected status 403
```

while trying to download the BPE map.

Fixed the above by changing the `read_file` function to using 
```python
def read_file(uri): 
  return requests.get(uri).content
```

Next error I got, which I haven't managed to fix, is:

```
blobfile.common.Error: Found storage account key, but it was unable to access storage account: 'openaipublic'
```

Would be really great to try out this model so hoping there is a solution for this! Cheers!

**Comment by CFLJacquet** [comment]
Hi I also tried to run the examples in local (after creating an Azure account) and run into this error

```
blobfile.common.Error: Found storage account key, but it was unable to access storage account: 'openaipublic'
```

**Comment by daniel-ziegler** [comment]
Sorry about that, this seems to be a `blobfile` issue. I've filed an issue there and will update this repo to the new version once it is fixed.

**Comment by daniel-ziegler** [comment]
Please give this another shot - hopefully it works now!

**Comment by CFLJacquet** [comment]
It seems like it still does not work but the error message is different this time. 

```
Traceback (most recent call last):
  File "exps/sample.py", line 6, in <module>
    from summarize_from_feedback.utils import experiment_helpers as utils
  File "/home/charles/Documents/code/summarize-from-feedback/summarize_from_feedback/utils/experiment_helpers.py", line 172, in <module>
    response_length = len(encoder.encode(x["reference"]))
  File "/home/charles/Documents/code/summarize-from-feedback/summarize_from_feedback/datasets/encodings.py", line 183, in encode
    self._load()
  File "/home/charles/Documents/code/summarize-from-feedback/summarize_from_feedback/datasets/encodings.py", line 110, in _load
    self._token_str_to_idx = json.loads(read_file(self.full_encoder_path).decode())
  File "/home/charles/Documents/code/summarize-from-feedback/summarize_from_feedback/datasets/encodings.py", line 15, in read_file
    with bf.BlobFile(path, "rb") as f:
  File "/home/charles/.local/share/virtualenvs/summarize-from-feedback-22wIJUlP/lib/python3.7/site-packages/blobfile/ops.py", line 2928, in BlobFile
    f = _AzureStreamingReadFile(path)
  File "/home/charles/.local/share/virtualenvs/summarize-from-feedback-22wIJUlP/lib/python3.7/site-packages/blobfile/ops.py", line 2455, in __init__
    isfile, self._metadata = _azure_isfile(path)
  File "/home/charles/.local/share/virtualenvs/summarize-from-feedback-22wIJUlP/lib/python3.7/site-packages/blobfile/ops.py", line 995, in _azure_isfile
    resp = _execute_azure_api_request(req)
  File "/home/charles/.local/share/virtualenvs/summarize-from-feedback-22wIJUlP/lib/python3.7/site-packages/blobfile/ops.py", line 573, in _execute_azure_api_request
    return _execute_request(build_req)
  File "/home/charles/.local/share/virtualenvs/summarize-from-feedback-22wIJUlP/lib/python3.7/site-packages/blobfile/ops.py", line 589, in _execute_request
    req = build_req()
  File "/home/charles/.local/share/virtualenvs/summarize-from-feedback-22wIJUlP/lib/python3.7/site-packages/blobfile/ops.py", line 570, in build_req
    req, auth=global_azure_access_token_manager.get_token(key=account)
  File "/home/charles/.local/share/virtualenvs/summarize-from-feedback-22wIJUlP/lib/python3.7/site-packages/blobfile/ops.py", line 270, in get_token
    self._tokens[key], self._expiration = self._get_token_fn(key)
  File "/home/charles/.local/share/virtualenvs/summarize-from-feedback-22wIJUlP/lib/python3.7/site-packages/blobfile/ops.py", line 502, in _azure_get_access_token
    f"Could not find any credentials that grant access to storage account: '{account}'"
blobfile.common.Error: Could not find any credentials that grant access to storage account: 'openaipublic'
```

**Comment by daniel-ziegler** [comment]
Hmm. What if you log out of Azure?

**Comment by daniel-ziegler** [comment]
I tried this again both logged out and logged in to an account that doesn't have any particular privileges; everything seems to work for me. Did you make sure to `pipenv install` again to update?
